server:
  port: 7070

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/noetipo/DAD_2023_2.git
          searchPaths: config-data
          #username:
          #password:
          default-label: main


  security:
    user:
      name: root
      password: s3cr3t

